spring.application.name=travelguide

spring.datasource.url=jdbc:mysql://localhost:3306/travelguide
spring.datasource.username=traveldestinationadmin
spring.datasource.password=travel123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkeyupdated32charsminimum!
jwt.expiration=3600000